version: '4'
services:
  init:
    image: busybox
    container_name: init_service
    volumes:
      - ./profile:/profile
    command: [ "sh", "-c", "mkdir -p /profile" , "mkdir -p /medicalFolder" ]
  mysql:
    image: mysql:8.4.0
    container_name: mysql_lms_service
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3311:3306" # change port as your need
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql